services:
  # Servicio Web / Frontend & Prototipo
  mcontrol-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcontrol_web
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./Proyecto:/usr/share/nginx/html:ro

  # Servicio de Inteligencia Artificial y EDA (Python 3.12, NumPy, Matplotlib)
  python_ia:
    build:
      context: .
      dockerfile: Dockerfile.ia
    container_name: python_ia
    volumes:
      - .:/app
    command: python eda_proyecto.py
